#Wed, 05 May 2021 20:21:42 -0700
#Ant properties
#Wed May 05 20:21:42 PDT 2021
-baselinerepo=remoterepo
-metatype=*
-plugin=aQute.bnd.deployer.repository.LocalIndexedRepo;local=L:/public/master-portal/.bnd/localrepo;name=localrepo;phase=any;type=R5,aQute.bnd.deployer.repository.FixedIndexedRepo;cache=L:/public/master-portal/.bnd/bndtoolsrepo;locations='https://github.com/bndtools/bundle-hub/raw/master/index.xml.gz';name=bndtoolsrepo;phase=any;type=R5,aQute.bnd.deployer.repository.FixedIndexedRepo;cache=L:/public/master-portal/.bnd/remoterepo;locations='http://obr.liferay.com/r5/liferay-portal/index.xml.gz';name=remoterepo;phase=any;type=R5
-releaserepo=localrepo
app.server.jboss.bin.dir=L:/public/master-bundles/jboss-eap-7.2.0/bin
app.server.jboss.classes.global.dir=L:/public/master-bundles/jboss-eap-7.2.0/modules/com/liferay/portal/main
app.server.jboss.classes.portal.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/deployments/ROOT.war/WEB-INF/classes
app.server.jboss.deploy.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/deployments
app.server.jboss.dir=L:/public/master-bundles/jboss-eap-7.2.0
app.server.jboss.instance.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone
app.server.jboss.lib.global.dir=L:/public/master-bundles/jboss-eap-7.2.0/modules/com/liferay/portal/main
app.server.jboss.lib.portal.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/deployments/ROOT.war/WEB-INF/lib
app.server.jboss.log.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/log
app.server.jboss.portal.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/deployments/ROOT.war
app.server.jboss.temp.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/tmp
app.server.jboss.work.dir=L:/public/master-bundles/jboss-eap-7.2.0/standalone/tmp/work
app.server.parent.dir=L:/public/master-bundles
app.server.tcserver.bin.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/bin
app.server.tcserver.classes.global.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/lib
app.server.tcserver.classes.portal.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/webapps/ROOT/WEB-INF/classes
app.server.tcserver.conf.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/conf
app.server.tcserver.deploy.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/webapps
app.server.tcserver.developer.dir=L:/public/master-bundles/tc-server-4.0.2/developer-4.0.2.RELEASE
app.server.tcserver.dir=L:/public/master-bundles/tc-server-4.0.2
app.server.tcserver.lib.endorsed.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/lib
app.server.tcserver.lib.global.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/lib
app.server.tcserver.lib.portal.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/webapps/ROOT/WEB-INF/lib
app.server.tcserver.lib.support.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/lib
app.server.tcserver.log.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/logs
app.server.tcserver.portal.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/webapps/ROOT
app.server.tcserver.temp.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/temp
app.server.tcserver.work.dir=L:/public/master-bundles/tc-server-4.0.2/instances/liferay/work
app.server.tomcat.bin.dir=L:/public/master-bundles/tomcat-9.0.37/bin
app.server.tomcat.classes.global.dir=L:/public/master-bundles/tomcat-9.0.37/lib
app.server.tomcat.classes.portal.dir=L:/public/master-bundles/tomcat-9.0.37/webapps/ROOT/WEB-INF/classes
app.server.tomcat.deploy.dir=L:/public/master-bundles/tomcat-9.0.37/webapps
app.server.tomcat.dir=L:/public/master-bundles/tomcat-9.0.37
app.server.tomcat.lib.endorsed.dir=L:/public/master-bundles/tomcat-9.0.37/lib/ext
app.server.tomcat.lib.global.dir=L:/public/master-bundles/tomcat-9.0.37/lib/ext
app.server.tomcat.lib.portal.dir=L:/public/master-bundles/tomcat-9.0.37/webapps/ROOT/WEB-INF/lib
app.server.tomcat.lib.support.dir=L:/public/master-bundles/tomcat-9.0.37/lib/ext
app.server.tomcat.log.dir=L:/public/master-bundles/tomcat-9.0.37/logs
app.server.tomcat.portal.dir=L:/public/master-bundles/tomcat-9.0.37/webapps/ROOT
app.server.tomcat.temp.dir=L:/public/master-bundles/tomcat-9.0.37/temp
app.server.tomcat.work.dir=L:/public/master-bundles/tomcat-9.0.37/work
app.server.type=tomcat
app.server.weblogic.bin.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/bin
app.server.weblogic.classes.global.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/lib
app.server.weblogic.classes.portal.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/autodeploy/ROOT/WEB-INF/classes
app.server.weblogic.deploy.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/autodeploy
app.server.weblogic.dir=L:/public/master-bundles/weblogic-12.2.1
app.server.weblogic.instance.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay
app.server.weblogic.lib.global.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/lib
app.server.weblogic.lib.portal.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/autodeploy/ROOT/WEB-INF/lib
app.server.weblogic.log.dir=L:/public/master-bundles/weblogic-12.2.1/liferay/log
app.server.weblogic.portal.dir=L:/public/master-bundles/weblogic-12.2.1/domains/liferay/autodeploy/ROOT
app.server.weblogic.temp.dir=L:/public/master-bundles/weblogic-12.2.1/liferay/log
app.server.weblogic.wlserver.dir=L:/public/master-bundles/weblogic-12.2.1/wlserver
app.server.weblogic.work.dir=L:/public/master-bundles/weblogic-12.2.1/liferay/log
app.server.websphere.bin.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/bin
app.server.websphere.classes.global.dir=L:/public/master-bundles/websphere-9.0.0.0/lib/ext
app.server.websphere.classes.portal.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/classes
app.server.websphere.deploy.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/wsadmin-deploy
app.server.websphere.dir=L:/public/master-bundles/websphere-9.0.0.0
app.server.websphere.instance.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay
app.server.websphere.lib.global.dir=L:/public/master-bundles/websphere-9.0.0.0/lib/ext
app.server.websphere.lib.portal.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/lib
app.server.websphere.log.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/logs/server1
app.server.websphere.portal.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war
app.server.websphere.temp.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/logs/server1
app.server.websphere.work.dir=L:/public/master-bundles/websphere-9.0.0.0/profiles/liferay/logs/server1
app.server.wildfly.bin.dir=L:/public/master-bundles/wildfly-14.0.0/bin
app.server.wildfly.classes.global.dir=L:/public/master-bundles/wildfly-14.0.0/modules/com/liferay/portal/main
app.server.wildfly.classes.portal.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/deployments/ROOT.war/WEB-INF/classes
app.server.wildfly.deploy.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/deployments
app.server.wildfly.dir=L:/public/master-bundles/wildfly-14.0.0
app.server.wildfly.instance.dir=L:/public/master-bundles/wildfly-14.0.0/standalone
app.server.wildfly.lib.global.dir=L:/public/master-bundles/wildfly-14.0.0/modules/com/liferay/portal/main
app.server.wildfly.lib.portal.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/deployments/ROOT.war/WEB-INF/lib
app.server.wildfly.log.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/log
app.server.wildfly.portal.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/deployments/ROOT.war
app.server.wildfly.temp.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/tmp
app.server.wildfly.work.dir=L:/public/master-bundles/wildfly-14.0.0/standalone/tmp/work
ivy.pom.developer.name=Brian Wing Shun Chan
ivy.pom.developer.organization=Liferay, Inc.
ivy.pom.developer.organizationUrl=http://www.liferay.com
ivy.pom.license.name=LGPL 2.1
ivy.pom.license.url=http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
ivy.pom.scm.connection=scm:git:git@github.com:liferay/liferay-portal.git
ivy.pom.scm.developerConnection=scm:git:git@github.com:liferay/liferay-portal.git
ivy.pom.scm.url=http://github.com/liferay/liferay-portal
junit.java.unit.gc=-Xms512m -Xmx512m -XX:MaxMetaspaceSize=128m -XX:MaxNewSize=32m -XX:MaxTenuringThreshold=0 -XX:MetaspaceSize=64m -XX:NewSize=32m -XX:ParallelGCThreads=2 -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0 -XX:-UseAdaptiveSizePolicy -XX:+UseParallelOldGC
junit.java.unit.gc.logging=off
junit.test.excludes=(?!)
liferay.home=L:/public/master-bundles
lp.version=7.4.10
microsoft.translator.subscription.key=
sass.compiler.class.name=jni
snapshot.check.enabled=true
sonatype.release.hostname=repository.liferay.com
sonatype.release.password=
sonatype.release.realm=Sonatype Nexus Repository Manager
sonatype.release.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases
sonatype.release.username=
sonatype.snapshot.hostname=repository.liferay.com
sonatype.snapshot.password=
sonatype.snapshot.realm=Sonatype Nexus Repository Manager
sonatype.snapshot.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-snapshots
sonatype.snapshot.username=
upgrade.table.dir=

ivy.repository.liferay.private.password=xrNnezhv4zhZzApn
ivy.repository.liferay.private.url=https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/
ivy.repository.liferay.private.username=private-20201009
lp.portal.project.dir=L:/public/master-portal
module.framework.base.dir=L:/public/master-bundles/osgi
